name: Build release .exe

on:
  release:
    types: [published]

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22

      - name: Build JAR with Ant
        shell: cmd
        run: |
          ant -Dproject.version="${{ github.ref_name }}" clean jar

      - name: Package .exe
        run: jpackage --type exe --input dist --dest dist --name SimuladorClp --main-jar SimuladorClp.jar --main-class SimuladorClp --win-menu --win-shortcut --win-dir-chooser --java-options "-Xmx512m"

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/SimuladorClp*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
